#pragma once
#include "pch.h"
#include "BasicTypes.h"
#include "Core/Vector3.h"
#include "Core/Vector2.h"

namespace LuxonEngine::Rendering::DX12 {
	/// <summary>
	/// Vertex generated by the spline compute shader. the layout must match the vertex input of the spline rasterization shaders
	/// </summary>
	struct SplineVertex {
		Vector3 position;
		Vector2 uv;
		Vector3 normal;
		Vector3 tangent;

		SplineVertex() : SplineVertex(Vector3(0.0f), Vector2(0.0f), Vector3(0.0f), Vector3(0.0f))
		{
		}

		SplineVertex(const Vector3& pos, const Vector2& tex, const Vector3& normal, const Vector3& tangent)
			:position(pos), uv(tex), normal(normal), tangent(tangent)
		{
		}
	};
}
